server:
  port: 8989


spring:
  application:
    name: gateway
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
    gateway: # config下GateConfig等效
      routes:
        - id: user_route
          # uri: http://localhost:9999
          uri: lb://users
          predicates:
            - Path=/feign/**
        - id: product_route
          # uri: http://localhost:9998 写死的 没有负载均衡
          uri: lb://products # lb 使用附在均衡策略 products代表注册中心的具体服务名
          predicates:
            - Path=/product/**
            # - After=2021-02-02T13:15:27.783+08:00[GMT+08:00]
            # - Before=2021-02-02T13:16:27.783+08:00[GMT+08:00]
            # - Between=2021-02-02T13:16:27.783+08:00[GMT+08:00],2021-02-02T13:19:27.783+08:00[GMT+08:00]
            # - Cookie=username,jdq
            # - Cookie=username,[A-Za-z0-9]+
            # - Header=X-Request-Id,\d+
            # - Method=Post
            # 经过predicates会经过filter
      #          filters:
      #            - AddRequestParameter=id,34
      #            - AddResponseHeader=username,jdq

      discovery:
        locator:
          enabled: true # 开启根据服务名动态获取路由地址

management:
  endpoints:
    web:
      exposure:
        include: "*"
